version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/docker
permissions:
  - object: /home/ec2-user/docker
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
